export type DocumentType =
  | 'pdf'
  | 'docx'
  | 'markdown'
  | 'text'
  | 'code'
  | 'spreadsheet'
  | 'email'
  | 'web';

export interface DocumentSummary {
  brief: string;
  detailed: string;
  keyPoints: string[];
  provider?: string;
}

export interface DocumentVersion {
  id: string;
  versionNumber: number;
  timestamp: string;
  title: string;
  content: string;
  summary: DocumentSummary;
  fileSize: number;
  chunksCount: number;
  tokenCount: number;
  tags: string[];
  category: string;
  changeDescription: string;
  author?: string;
}

export interface DocumentItem {
  id: string;
  title: string;
  filePath: string;
  fileType: DocumentType;
  fileSize: number; // in bytes
  hash: string;
  createdAt: string;
  updatedAt: string;
  category: string;
  tags: string[];
  chunksCount: number;
  tokenCount: number;
  content: string;
  summary: DocumentSummary;
  relevanceScore?: number;
  matchedSnippet?: string;
  embeddingModel?: string;
  version?: number;
  versions?: DocumentVersion[];
}

export interface OpenRouterModelInfo {
  id: string;
  name: string;
  description?: string;
  context_length?: number;
  pricing?: {
    prompt: string | number;
    completion: string | number;
  };
  isFree?: boolean;
}

export interface LMStudioModelInfo {
  id: string;
  object?: string;
  owned_by?: string;
}

export interface CategoryItem {
  id: string;
  name: string;
  iconName: string;
  count: number;
  color: string;
  description?: string;
}

export interface WikiTocItem {
  id: string;
  title: string;
  level: number;
}

export type WikiStatus = 'auto' | 'user-edited' | 'locked';

export interface WikiSection {
  id: string;
  heading: string;
  level: number;
  content: string;
  sourceDocIds?: string[];
}

export interface WikiLink {
  sourcePageId: string;
  targetPageId: string;
  linkText: string;
  contextText?: string;
}

export interface WikiPageSource {
  documentId: string;
  documentTitle: string;
  relevanceScore: number;
  matchedSnippet?: string;
}

export interface WikiContradiction {
  id: string;
  topic: string;
  statementA: string;
  sourceDocA: string;
  statementB: string;
  sourceDocB: string;
  notes: string;
}

export interface WikiKnowledgeGap {
  id: string;
  topic: string;
  description: string;
  suggestedResearch: string;
  importance: 'high' | 'medium' | 'low';
}

export interface WikiCluster {
  id: string;
  name: string;
  description: string;
  category: string;
  documentIds: string[];
  primaryWikiId?: string;
  subtopics: string[];
  confidenceScore: number;
  stalenessCount: number;
}

export interface WikiPage {
  id: string;
  title: string;
  slug?: string;
  summary: string;
  content: string;
  originalContent?: string;
  category: string;
  clusterId?: string;
  status?: WikiStatus;
  coverageScore?: number; // 0 - 100%
  lastUpdated: string;
  lastGeneratedAt?: string;
  userEditedAt?: string;
  sourceDocIds: string[];
  sources?: WikiPageSource[];
  sections?: WikiSection[];
  contradictions?: WikiContradiction[];
  knowledgeGaps?: WikiKnowledgeGap[];
  backlinks?: string[];
  stalenessCount?: number;
  autoGenerated?: boolean;
}

export interface SettingsConfig {
  aiProvider: 'lmstudio' | 'openrouter' | 'gemini' | 'hybrid' | 'local-slm' | 'xai';
  lmStudioUrl: string;
  openRouterApiKey?: string;
  openRouterModel?: string;
  xaiApiKey?: string;
  xaiModel?: string;
  embeddingModel?: string;
  chatModel?: string;
  chunkSize: number;
  chunkOverlap: number;
  chunkSizeTokens?: number;
  chunkOverlapTokens?: number;
  theme: 'dark' | 'light';
  storageLocation?: string;
  lanceDbPath?: string;
  sqlitePath?: string;
  hybridWeightSemantic?: number;
  hybridWeightKeyword?: number;
}

export interface SearchResult {
  document: DocumentItem;
  score: number;
  searchType: 'semantic' | 'keyword' | 'hybrid';
  matchedSnippet: string;
  chunkIndex?: number;
}

export interface IngestionJob {
  id: string;
  fileName: string;
  fileSize: number;
  fileType: DocumentType;
  status: 'queued' | 'parsing' | 'chunking' | 'embedding' | 'categorizing' | 'summarizing' | 'completed' | 'failed';
  progress: number; // 0 - 100
  chunksCount?: number;
  tokensCount?: number;
  category?: string;
  error?: string;
}

export interface ToastMessage {
  id: string;
  type: 'info' | 'success' | 'warning' | 'error';
  title: string;
  message?: string;
}

export type ActiveTab = 'library' | 'search' | 'document' | 'wiki' | 'settings';
